<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-18T17:01:58 IST" name="Default suite" finished-at="2023-09-18T17:02:26 IST" duration-ms="28453">
    <groups>
    </groups>
    <test started-at="2023-09-18T17:01:58 IST" name="Default test" finished-at="2023-09-18T17:02:26 IST" duration-ms="28453">
      <class name="com.qa.testCases.Test_Login_Page">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:01:58 IST" name="setup" finished-at="2023-09-18T17:02:14 IST" duration-ms="16121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testLoginPage()[pri:0, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:02:14 IST" name="testLoginPage" finished-at="2023-09-18T17:02:15 IST" duration-ms="882" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:02:15 IST" name="tearDown" finished-at="2023-09-18T17:02:15 IST" duration-ms="131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:02:15 IST" name="setup" finished-at="2023-09-18T17:02:22 IST" duration-ms="6838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test1()[pri:2, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:02:22 IST" name="test1" finished-at="2023-09-18T17:02:22 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:02:22 IST" name="tearDown" finished-at="2023-09-18T17:02:22 IST" duration-ms="126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:02:22 IST" name="setup" finished-at="2023-09-18T17:02:26 IST" duration-ms="4138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test2()[pri:3, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:02:26 IST" name="test2" finished-at="2023-09-18T17:02:26 IST" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [B] but found [A]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [B] but found [A]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.qa.testCases.Test_Login_Page.test2(Test_Login_Page.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:02:26 IST" name="tearDown" finished-at="2023-09-18T17:02:26 IST" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="test3()[pri:4, instance:com.qa.testCases.Test_Login_Page@2892d68]" started-at="2023-09-18T17:02:26 IST" name="test3" finished-at="2023-09-18T17:02:26 IST" depends-on-methods="com.qa.testCases.Test_Login_Page.test2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.qa.testCases.Test_Login_Page.test3() on instance com.qa.testCases.Test_Login_Page@2892d68 depends on not successfully finished methods 
[com.qa.testCases.Test_Login_Page.test2() on instance com.qa.testCases.Test_Login_Page@2892d68]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.qa.testCases.Test_Login_Page.test3() on instance com.qa.testCases.Test_Login_Page@2892d68 depends on not successfully finished methods 
[com.qa.testCases.Test_Login_Page.test2() on instance com.qa.testCases.Test_Login_Page@2892d68]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- com.qa.testCases.Test_Login_Page -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
